<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CopiousCare" failures="0" tests="15" name="pivotalApplication.FitCertificate" time="256.979" errors="1" timestamp="2024-04-16T11:44:19 IST" skipped="0">
  <testcase classname="pivotalApplication.FitCertificate" name="BfSuite" time="0.804"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="NumberField" time="2.030"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="IAgree" time="2.173"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="proceedButton" time="2.368"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="OTP" time="10.949"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="submit" time="13.146"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="Search" time="11.152"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="ClickPatient" time="17.910"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="Certificate" time="27.561"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="CertificateDropdown" time="22.288"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="CertificateType" time="22.281"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="Speciality" time="32.439"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="SpecialitySelect" time="37.285"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="Preview" time="52.408"/>
  <system-out/>
  <testcase classname="pivotalApplication.FitCertificate" name="Print" time="2.185">
    <error message="Index 0 out of bounds for length 0" type="java.lang.IndexOutOfBoundsException">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at pivotalApplication.FitCertificate.Print(FitCertificate.java:191)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Print -->
  <system-out/>
</testsuite> <!-- pivotalApplication.FitCertificate -->
